image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - dotnet --version
  - cd content/StsServerIdentity
  - dotnet restore
build_script:
- cd content/StsServerIdentity
- dotnet build
before_build:
- appveyor-retry dotnet restore -v Minimal

